const challenges = [
  {
    title: 'No Jajan 3 Hari',
    description: 'Tahan diri untuk tidak jajan selama 3 hari',
    icon: 'self_improvement',
    difficulty: 'easy',
    xp_reward: 50,
    days_required: 3,
    requirement_type: 'no_category',
    requirement_value: 'Jajan',
  },
  {
    title: 'Catat Harian',
    description: 'Catat transaksi setiap hari selama 7 hari',
    icon: 'calendar_month',
    difficulty: 'easy',
    xp_reward: 75,
    days_required: 7,
    requirement_type: 'daily_log',
    requirement_value: '7',
  },
  {
    title: 'Hemat Transport',
    description: 'Kurangi pengeluaran transport 50% minggu ini',
    icon: 'directions_bus',
    difficulty: 'medium',
    xp_reward: 100,
    days_required: 7,
    requirement_type: 'reduce_category',
    requirement_value: 'Transport',
  },
  {
    title: 'Budget Warrior',
    description: 'Buat budget untuk 3 kategori bulan ini',
    icon: 'account_balance_wallet',
    difficulty: 'medium',
    xp_reward: 100,
    days_required: 1,
    requirement_type: 'create_budget',
    requirement_value: '3',
  },
  {
    title: 'Makan di Rumah',
    description: 'Kurangi jajan di luar, makan di rumah 5 hari',
    icon: 'home',
    difficulty: 'medium',
    xp_reward: 150,
    days_required: 5,
    requirement_type: 'no_category',
    requirement_value: 'Makan',
  },
  {
    title: 'Zero Waste Week',
    description: 'Hanya belanja kebutuhan pokok selama seminggu',
    icon: 'recycling',
    difficulty: 'hard',
    xp_reward: 200,
    days_required: 7,
    requirement_type: 'reduce_expense',
    requirement_value: '20',
  },
  {
    title: 'Save Rp 100K',
    description: 'Berhasil menyisihkan Rp 100.000 dalam seminggu',
    icon: 'savings',
    difficulty: 'hard',
    xp_reward: 250,
    days_required: 7,
    requirement_type: 'save_amount',
    requirement_value: '100000',
  },
  {
    title: 'Financial Detective',
    description: 'Catat 20 transaksi dalam seminggu',
    icon: 'search',
    difficulty: 'easy',
    xp_reward: 50,
    days_required: 7,
    requirement_type: 'transaction_count',
    requirement_value: '20',
  },
];

module.exports = challenges;
